require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3.1
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
