# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

group :test, :development do
  gem 'byebug', '~> 11.1'
  gem 'rake', '~> 13.0'
  gem 'rspec', '~> 3.0'
  gem 'rubocop', '~> 1.21'
  gem 'rubocop-rake', '~> 0.6', require: false
  gem 'rubocop-rspec', '~> 2.29', require: false
end
