# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in dndarena.gemspec
gemspec

group :test, :development do
  gem 'byebug'
  gem 'rake', '~> 13.0', '>= 13.2.1'
  gem 'rspec', '~> 3.0', '>= 3.13.0'
  gem 'rubocop', '~> 1.21', '>= 1.64.0'
  gem 'rubocop-rake', require: false
  gem 'rubocop-rspec', require: false
end
